# Builder 
FROM arm64v8/node:14-alpine as builder

RUN apk add --no-cache make gcc g++ python

WORKDIR /app

COPY . .

RUN yarn && yarn build

# Production
FROM arm64v8/node:14-alpine

COPY --from=builder /app/package.json /app/
COPY --from=builder /app/yarn.lock /app/

RUN yarn --production

COPY --from=builder /app/.next /app/.next

ENTRYPOINT yarn start